# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Preprocess": "00_preprocess.ipynb"}

modules = ["preprocess.py"]

doc_url = "https://Sylvia9628.github.io/test_nbdev/"

git_url = "https://github.com/Sylvia9628/test_nbdev/tree/master/"

def custom_doc_links(name): return None
